spring.application.name=SISTEMAPRESTAMO

spring.datasource.url=jdbc:mysql://localhost:3306/SISTEMAPRESTAMO
spring.datasource.username=app_prestamos
spring.datasource.password=AppPrestamos123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#no le permitimos a hibernate trabajar de forma directa con mysql
spring.jpa.hibernate.ddl-auto=none
#nos muestra las sentencias de mysql antes de ejecutar
spring.jpa.show-sql=true 
#desactivamos asi no levanta el servidor por ahora
spring.main.web-application-type=none